### ISSUE TITLE
Cannot render correctly under Node v4 LTS and Hexo 3.2.2

### ISSUE THREAD

**Issue by TommyLau** [HoverBaum/meilidu-hexo#3]
As title, when running `hexo s`, got following errors:

```
INFO  Start processing
ERROR Process failed: layout/category.ejs
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in "/path/to/blog/themes/meilidu/layout/category.ejs"
    at Function (native)
    at Object.exports.compile (/path/to/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14)
    at Function.ejsRenderer.compile (/path/to/blog/node_modules/hexo-renderer-ejs/lib/renderer.js:11:14)
    at View._precompile (/path/to/blog/node_modules/hexo/lib/theme/view.js:119:29)
    at View (/path/to/blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/path/to/blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/path/to/blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /path/to/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at /path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /path/to/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Process failed: layout/categories.ejs
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in "/path/to/blog/themes/meilidu/layout/categories.ejs"
    at Function (native)
    at Object.exports.compile (/path/to/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14)
    at Function.ejsRenderer.compile (/path/to/blog/node_modules/hexo-renderer-ejs/lib/renderer.js:11:14)
    at View._precompile (/path/to/blog/node_modules/hexo/lib/theme/view.js:119:29)
    at View (/path/to/blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/path/to/blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/path/to/blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /path/to/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at /path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /path/to/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Process failed: layout/archive.ejs
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in "/path/to/blog/themes/meilidu/layout/archive.ejs"
    at Function (native)
    at Object.exports.compile (/path/to/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14)
    at Function.ejsRenderer.compile (/path/to/blog/node_modules/hexo-renderer-ejs/lib/renderer.js:11:14)
    at View._precompile (/path/to/blog/node_modules/hexo/lib/theme/view.js:119:29)
    at View (/path/to/blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/path/to/blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/path/to/blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /path/to/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at /path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /path/to/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Process failed: layout/layout.ejs
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in "/path/to/blog/themes/meilidu/layout/layout.ejs"
    at Function (native)
    at Object.exports.compile (/path/to/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14)
    at Function.ejsRenderer.compile (/path/to/blog/node_modules/hexo-renderer-ejs/lib/renderer.js:11:14)
    at View._precompile (/path/to/blog/node_modules/hexo/lib/theme/view.js:119:29)
    at View (/path/to/blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/path/to/blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/path/to/blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /path/to/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at /path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /path/to/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Process failed: layout/tags.ejs
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in "/path/to/blog/themes/meilidu/layout/tags.ejs"
    at Function (native)
    at Object.exports.compile (/path/to/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14)
    at Function.ejsRenderer.compile (/path/to/blog/node_modules/hexo-renderer-ejs/lib/renderer.js:11:14)
    at View._precompile (/path/to/blog/node_modules/hexo/lib/theme/view.js:119:29)
    at View (/path/to/blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/path/to/blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/path/to/blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /path/to/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at /path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /path/to/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Process failed: layout/tag.ejs
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in "/path/to/blog/themes/meilidu/layout/tag.ejs"
    at Function (native)
    at Object.exports.compile (/path/to/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14)
    at Function.ejsRenderer.compile (/path/to/blog/node_modules/hexo-renderer-ejs/lib/renderer.js:11:14)
    at View._precompile (/path/to/blog/node_modules/hexo/lib/theme/view.js:119:29)
    at View (/path/to/blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/path/to/blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/path/to/blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /path/to/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at /path/to/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /path/to/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by HoverBaum** [comment]
Hi, thanks for bringing this up. 

That is an error you see due to the theme using some ES6 syntax which is supported in Node 6.x (not sure if earlier, you might try the `--harmony` flag).

This should really be added to the documentation as a pre-requiry to using the theme.

**Comment by TommyLau** [comment]
Are you planning to support the LTS version in the future? IMO, most people would rather using LTS version, switching versions sometimes could be annoying, even with the help of 'n' or 'nvm'.

**Comment by HoverBaum** [comment]
@TommyLau I see the advantages of LTS, especially for more "casual" users of Node. Though I really want to stick with the few ES6 features I am using. For on because I feel the syntax is much cleaner and because this will be where the language moves to in the future.

The [LTS schedule](https://github.com/nodejs/LTS#lts-schedule) for Node actually states that v6 will be in LTS from October 2016. So I guess in a bit over a month we can have the best of both worlds :smiley: 

Alternatively it could be possible to make a fork of the EJS renderer that runs things in strict mode. That might give us support for Node v4. But might not be enough and honestly so far I have found dealing with renderers for Hexo to far more trouble than it is worth. So I would rather not go there but wait for v6 to hit LTS.

**Comment by TommyLau** [comment]
@HoverBaum Yes, I'm also waiting for the Oct 2016 version LTS, hope it will come sooner. And out of the topic, you chose a Chinese name as the theme name, did you ever learn Chinese?

**Comment by HoverBaum** [comment]
@TommyLau Enough to say hello and goodbye. Currently in China. That and Hexo being so chinese inspired me to just plug a few things into google translate and pick something that sounded nice ^^

Will close for now. There is now a notice in the documentation, hope that helps people until v6 is LTS.
