### ISSUE TITLE
 failed: layout/archive.ejs

### ISSUE THREAD

**Issue by Sanjay-F** [HoverBaum/meilidu-hexo#7]
hi,i got this error. 
what to do  next ?

V1.0 

```

ERROR Process failed: layout/archive.ejs
SyntaxError: Unexpected token => in "C:\\Users\\Sanjay\\Desktop\\hexo\\themes\\m                                                    eilidu\\layout\\archive.ejs"
    at Function (native)
    at Object.exports.compile (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo-re                                                    nderer-ejs\node_modules\ejs\lib\ejs.js:242:14)
    at Function.ejsRenderer.compile (C:\Users\Sanjay\Desktop\hexo\node_modules\h                                                    exo-renderer-ejs\lib\renderer.js:11:14)
    at View._precompile (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\lib\them                                                    e\view.js:119:29)
    at View (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\lib\theme\view.js:13                                                    :8)
    at new Theme._View.View (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\lib\                                                    theme\index.js:37:10)
    at Theme.setView (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\lib\theme\i                                                    ndex.js:71:20)
    at C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\lib\theme\processors\view.                                                    js:14:14
    at tryCatcher (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\node_modules\b                                                    luebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Sanjay\Desktop\hexo\node_modu                                                    les\hexo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\no                                                    de_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\n                                                    ode_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\n                                                    ode_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\node_mod                                                    ules\bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\                                                    node_modules\bluebird\js\release\promise.js:431:57)
    at Promise._settlePromiseFromHandler (C:\Users\Sanjay\Desktop\hexo\node_modu                                                    les\hexo\node_modules\bluebird\js\release\promise.js:522:17)
    at Promise._settlePromise (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\no                                                    de_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\n                                                    ode_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\n                                                    ode_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\node_mod                                                    ules\bluebird\js\release\promise.js:636:18)
    at C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\node_modules\bluebird\js\r                                                    elease\nodeback.js:42:21
    at C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\node_modules\hexo-fs\node_                                                    modules\graceful-fs\graceful-fs.js:78:16
    at fs.js:334:14
    at C:\Users\Sanjay\Desktop\hexo\node_modules\hexo-deployer-git\node_modules\                                                    hexo-fs\node_modules\chokidar\node_modules\readdirp\node_modules\graceful-fs\gra                                                    ceful-fs.js:104:5
    at C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\node_modules\nunjucks\node                                                    _modules\chokidar\node_modules\readdirp\node_modules\graceful-fs\graceful-fs.js:                                                    43:10
    at C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\node_modules\hexo-fs\node_                                                    modules\graceful-fs\graceful-fs.js:43:10
    at C:\Users\Sanjay\Desktop\hexo\node_modules\hexo\node_modules\warehouse\nod                                                    e_modules\graceful-fs\graceful-fs.js:43:10
    at C:\Users\Sanjay\AppData\Roaming\npm\node_modules\hexo\node_modules\hexo-f                                                    s\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:95:15)

```

**Comment by HoverBaum** [comment]
Ahh it might be that you node Version is below v6. The template uses some ES6 features. These are not enabled by default before Node v6.

Try `node -v` and see the version. 
You can get the latest version of Node at https://nodejs.org/
You can read #3 for some more information on the supported Node version.
