### ISSUE TITLE
Hexo generate failure

### ISSUE THREAD

**Issue by hwding** [HoverBaum/meilidu-hexo#9]
```
ERROR Process failed: layout/category.ejs
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in "/home/hwding/Documents/hwding.github.io/themes/meilidu/layout/category.ejs"
    at Function (native)
    at Object.exports.compile (/home/hwding/Documents/hwding.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14)
    at Function.ejsRenderer.compile (/home/hwding/Documents/hwding.github.io/node_modules/hexo-renderer-ejs/lib/renderer.js:11:14)
    at View._precompile (/home/hwding/Documents/hwding.github.io/node_modules/hexo/lib/theme/view.js:119:29)
    at View (/home/hwding/Documents/hwding.github.io/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/home/hwding/Documents/hwding.github.io/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/home/hwding/Documents/hwding.github.io/node_modules/hexo/lib/theme/index.js:71:20)
    at /home/hwding/Documents/hwding.github.io/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at /home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/hwding/Documents/hwding.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

using node v4.6.1 on Fedora

**Comment by HoverBaum** [comment]
Hi, sorry for a late reply. This is an issue with your node Version as the theme uses some ES6 feautres. Please make sure to use Node v6 or higher.

You can find some further discussion about this in https://github.com/HoverBaum/meilidu-hexo/issues/3
